setopt rcs
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}
export XDG_STATE_HOME=${XDG_STATE_HOME:="$HOME/.local/state"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export EDITOR="nvim"
export BROWSER="brave-nightly" 
export TERMINAL="alacritty" 
export EXA_ICON_SPACING="2" 
export TERM='xterm-256color'
export VISUAL='nvim'
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/bin/toggles:$PATH"
export PATH="$HOME/.emacs.d/bin:$PATH"
export PATH="$HOME/.tmuxifier/bin:$PATH"
export PNPM_HOME=${XDG_DATA_HOME:="$HOME/.local/share/pnpm"} 
export PATH="$PNPM_HOME:$PATH"
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"\
" --color=bg+:#073642,bg:#002b36,spinner:#2aa198,hl:#268bd2"\
" --color=fg:#839496,header:#268bd2,info:#b58900,pointer:#2aa198"\
" --color=marker:#2aa198,fg+:#eee8d5,prompt:#b58900,hl+:#268bd2"

