#!/bin/sh

while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-R")
                convert -rotate -90 "$file" "$file" ;;
        "C-c")
                cat "$file" | xclip -selection clipboard -target image/png -i &&
                notify-send "copied to clipboard" --icon="$file" ;;
        "C-w")
                nitrogen --set-zoom-fill --random --save "$file" ;;
        esac
done
