set -g default-terminal "tmux-256color"
set-option -a terminal-features 'alacritty:RGB'
set -g mouse on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Start windows and panes at 1, not 0
set -g pane-base-index 1
set -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c '#{pane_current_path}'
bind '%' split-window -h -c '#{pane_current_path}'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Colors
set -g @bg '#191724'
set -g @fg '#e0def4'
set -g @ac '#f6c177'
set -g @bd '#26233a'

# Pane separators
set -g pane-border-lines 'simple'
set -g pane-border-style 'fg=#{@fg},bright'
set -g pane-active-border-style 'fg=#{@fg}'

# Status bar
set -g status-position 'top'
set -g status-bg 'default'
set -g status-style 'fg=#{@fg}'
set -g status-left ''
set -g status-right ' 󰆧 #S '

set -g window-status-format ' #W '
set -g window-status-current-format ' #W '
set -g window-status-bell-style 'bg=red,nobold'
set -g window-status-current-style "fg=#{@ac},bg=#{?window_zoomed_flag,red,#{@bd}},nobold"

set -g @continuum-restore 'on'

bind-key "T" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

bind-key g display-popup -w 90% -h 90% -E "lazygit"

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'
