#!/bin/sh

draw() {
  kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
  exit 1
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type "$file")" in 
  image/*) draw "$file" ;;
  video/*) draw "$(~/.config/lf/scripts/thumbnails/vidthumb "$file")" ;;
  text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
  text/troff) man ./ "$1" | col -b ;;
  text/* | */xml | application/json) bat --terminal-width "$(($4-2))" -f "$1" ;;
  application/zip | application/tar | application/gzip | application/bzip2 | application/xz | application/7z-compressed) ouch list "$1" ;;
  audio/* | application/octet-stream) mediainfo "$1" || exit 1 ;;
  application/pgp-encrypted) gpg -d -- "$1" ;;
  application/pdf) draw "$(~/.config/lf/scripts/thumbnails/pdfthumb "$file")" ;;
  application/epub+zip) draw "$(~/.config/lf/scripts/thumbnails/epubthumb "$file")" ;;
  *) bat --terminal-width "$(($4-2))" -f "$1" ;;
esac
