$bg = 191724 
$fg = e0def4 
$font = Iosevka Nerd Font

background {
    path = screenshot
    blur_passes = 2
}

general {
    hide_cursor = true
    ignore_empty_input = true
}

# Time
label {
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgb($fg)
    font_family = $font 
    font_size = 96
    position = 0, 120 
}

# Day-Month-Date
label {
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, .7)
    font_size = 24
    font_family = $font
}

# INPUT FIELD
input-field {
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2 
    dots_spacing = 0.2
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    font_family = $font
    placeholder_text = <i><span foreground="##ffffff99">Enter Password</span></i>
    position = 0, -120
    rounding = 1
}
