format = """$directory$git_branch$git_status$character"""
right_format = """$all"""

add_newline = false
palette = "tokyonight"

[directory]
style = 'bold fg:blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'~' = ""
'documents' = '󰈙'
'downloads' = ' '
'music' = ' '
'pictures' = ' '

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[character]
error_symbol = "[ ](bold red)"
success_symbol = "[](bold blue)"

[palettes.tokyonight]
mono0 = '#c0caf5'         # Brightest Foreground
mono1 = '#a9b1d6'         # Main Foreground
mono2 = '#9aa5ce'         # Dim Foreground
mono3 = '#565f89'         # Comments/Non-active
mono4 = '#414868'         # Darker Gray/Selection
color_red0 = '#f7768e'    # Light Red
color_red1 = '#db4b4b'    # Dark Red
color_green = '#9ece6a'   # Green
color_yellow = '#e0af68'  # Yellow
color_blue = '#7aa2f7'    # Blue
color_purple = '#bb9af7'  # Purple
color_cyan = '#7dcfff'    # Cyan
color_orange = '#ff9e64'  # Orange
syntax_fg = '#c0caf5'     # Default Text
syntax_bg = '#1a1b26'     # Main Background
color_bg2 = '#24283b'     # Secondary Background
syntax_gutter = '#3b4261' # Gutter/Sidebar
syntax_accent = '#7aa2f7' # Primary Accent (Blue)
