format = """$directory$git_branch$git_status$character"""
right_format = """$all"""

add_newline = false
palette = "tokyonight"

[directory]
style = 'bold fg:yellow'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'~' = ""
'documents' = '󰈙'
'downloads' = ' '
'music' = ' '
'pictures' = ' '

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[character] 
success_symbol = '[](bold #7aa2f7)' 

[palettes.tokyonight]
color_fg0 = '#c0caf5'
color_bg0 = '#1a1b26'
color_bg1 = '#414868'
color_black = '#15161e'
color_red = '#f7768e'
color_green = '#9ece6a'
color_yellow = '#e0af68'
color_blue = '#7aa2f7'
color_magenta = '#bb9af7'
color_cyan = '#7dcfff'
color_white = '#a9b1d6'
