format = """$directory$git_branch$git_status$character"""
right_format = """$all"""

add_newline = false
palette = "rose-pine"

[directory]
style = 'bold fg:blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'~' = ""
'documents' = '󰈙'
'downloads' = ' '
'music' = ' '
'pictures' = ' '

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[character]
error_symbol = "[ ](bold red)"
success_symbol = "[ ](bold gold)"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
