format = """$directory$git_branch$git_status$character"""
right_format = """$all"""

add_newline = false
palette = "gruvbox-dark"

[directory]
style = 'bold fg:yellow'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'~' = ""
'documents' = '󰈙'
'downloads' = ' '
'music' = ' '
'pictures' = ' '

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"

[palettes.gruvbox-dark]
background = "#3c3836"
current_line = "#665c54"
foreground = "#fbf1c7"
comment = "#689d6a"
cyan = "#458588"
green = "#98971a"
orange = "#d65d0e"
pink = "#b16286"
purple = "#b16286"
red = "#cc241d"
yellow = "#d79921"
