#!/usr/bin/env bash

# AUTOSTART
$HOME/.config/bspwm/scripts/autostart.sh &
$HOME/.config/bspwm/scripts/window-borders.sh &

# BSPWM CONFIG
bspc monitor eDP-1 -d 1 2 3 4 5
# bspc monitor HDMI-2 -d 6 7 8 9 10

# borders & gaps
bspc config border_width                  2
bspc config window_gap                    5

# paddings
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0

# bspc rules
bspc config single_monocle                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config ignore_ewmh_focus 		  	    true

# modkey settings
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

bspc config normal_border_color           "#565f89"
bspc config focused_border_color          "#86e1fc"
bspc config active_border_color           "#86e1fc"
bspc config presel_feedback_color         "#86e1fc" 

# window rules
bspc rule -a Brave-browser-nightly desktop=^2 follow=true
bspc rule -a ChatGPT desktop=^5 follow=false
bspc rule -a VSCodium desktop=^1 follow=false
bspc rule -a Pulsemixer state=tiled desktop=^3 follow=on
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a Gpick state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Timeshift-gtk state=floating follow=on
bspc rule -a Xfce4-power-manager-settings state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Engrampa state=floating follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a Anki desktop=^1 state=monocole follow=false
bspc rule -a stacer state=floating
bspc rule -a Lightdm-gtk-greeter-settings state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a obsidian desktop=^4 follow=false
bspc rule -a Screenkey manage=off





