return {}

-- return {
--   "lukas-reineke/indent-blankline.nvim",
--   main = "ibl",
--   ---@module "ibl"
--   ---@type ibl.config
--   config = function()
--     require("ibl").setup({
--       indent = {
--         -- char = "╎",
--         char = "│",
--       },
--       scope = {
--         show_start = false,
--         show_end = false,
--         show_exact_scope = false,
--       },
--       exclude = {
--         filetypes = {
--           "help",
--           "startify",
--           "dashboard",
--           "packer",
--           "neogitstatus",
--           "NvimTree",
--           "Trouble",
--           "oil",
--         },
--       },
--     })
--   end,
-- }
