[env]
TERM = "xterm-256color"

[general]
live_config_reload = true
working_directory = "None"
import = ["/home/upal/.config/alacritty/themes/tokyonight_moon.toml"]

[window]
dynamic_padding = false
dynamic_title = true
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 8
y = 8

[window.position]
x = 0
y = 0

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
thickness = 0
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Beam"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 12.0

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 5 

[font.offset]
x = 1
y = 14 

[scrolling]
history = 10000

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"


